#!/bin/sh

# Install Git LFS
echo "Initializing Git LFS..."
# curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
# microdnf install git-lfs -y
git lfs install

# Clone the LFS-configured repository
echo "Cloning repository with Git LFS..."
git lfs clone ${DRONE_REMOTE_URL} ${DRONE_WORKSPACE}

echo "Git LFS clone completed."
ls .